class profile::security_policies {
  resources { 'panos_security_policy_rule':
    purge => true,
  }

  panos_security_policy_rule { 'lan-internet':
    ensure => 'present',
    rule_type => 'universal',
    source_zones => ['LAN'],
    source_address => ['192.168.0.0/24'],
    negate_source => false,
    source_users => ['any'],
    hip_profiles => ['any'],
    destination_zones => ['Internet'],
    destination_address => ['any'],
    negate_destination => false,
    applications => ['any'],
    services => ['any'],
    categories => ['any'],
    action => 'allow',
    icmp_unreachable => false,
    log_start => false,
    log_end => false,
    profile_type => 'none',
    qos_type => 'none',
    disable_server_response_inspection => false,
    disable => false,
    insert_after => '',
    require => [ Panos_zone['Internet'], Panos_zone['LAN'] ]
  }

  panos_security_policy_rule { 'hundo':
    ensure => 'present',
    source_zones => ['any'],
    source_address => ['any'],
    negate_source => false,
    source_users => ['any'],
    hip_profiles => ['any'],
    destination_zones => ['any'],
    destination_address => ['100.64.0.0-100.127.255.255'],
    negate_destination => false,
    applications => ['any'],
    services => ['application-default'],
    categories => ['any'],
    action => 'allow',
    icmp_unreachable => false,
    log_start => false,
    log_end => false,
    profile_type => 'none',
    qos_type => 'none',
    disable_server_response_inspection => false,
    disable => false,
    insert_after => 'lan-internet',
  }

  panos_security_policy_rule { 'siri':
    ensure => 'present',
    source_zones => ['LAN'],
    source_address => ['any'],
    negate_source => false,
    source_users => ['any'],
    hip_profiles => ['any'],
    destination_zones => ['any'],
    destination_address => ['any'],
    negate_destination => false,
    applications => ['apple-siri'],
    services => ['application-default'],
    categories => ['any'],
    action => 'allow',
    icmp_unreachable => false,
    log_start => false,
    log_end => false,
    profile_type => 'none',
    qos_type => 'none',
    disable_server_response_inspection => false,
    disable => false,
    insert_after => 'hundo',
  }
}